# Generated by Django 2.2.6 on 2019-10-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrating',
            name='score',
            field=models.PositiveIntegerField(),
        ),
    ]
